import LandingPage from "@/modules/Landing";
import ApiService from "@/services/api";
import TestService from "@/services/test";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

ApiService.init("https://randomuser.me/api/");

const data = async () => await TestService.Get();

export default async function Home() {
	const user = await data();
	return <LandingPage />;
}
